Add flat badges to gh-pages branch
sindresorhus/awesome pull request #1269
Opened 2018-04-08 10:54 UTC by bokub

Related to #1268

2018-04-09 08:55 UTC, merged

2022-02-05 22:41 UTC, 0566616453 commented
Leave a comment

2022-04-13 05:47 UTC, nassarjjjj commented
السلام

2022-07-28 10:16 UTC, GlatnahHapa approved these changes

2022-08-31 13:39 UTC, Javidmj approved these changes

2022-08-31 13:40 UTC, Javidmj approved these changes

2023-05-09 23:21 UTC, Porpasad commented
awesome.re

2024-11-13 13:14 UTC, Winn1993 approved these changes

2024-12-25 06:23 UTC, 30031987Ya commented
> Related to #1268

2024-12-25 06:43 UTC, Tester1234537 commented
Nao.. is what the men intehliveru en the bak.and pss the
 Visión is esy.. O we an the kill


El mié, 25 dic 2024, 1:31 a. m., 30031987Ya ***@***.***>
escribió:

> Related to #1268 <https://github.com/sindresorhus/awesome/pull/1268>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sindresorhus/awesome/pull/1269#issuecomment-2561649852>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7TCOKOUUO52CVS3RPMI4VL2HJGNNAVCNFSM6AAAAABRWO4PUOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRRGY2DSOBVGI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-01-01 23:41 UTC, surfo891 requested changes
Nonsirv

2025-02-02 12:52 UTC, Diego863 approved these changes
badge-flat.svg

2025-02-08 16:54 UTC, AngSolids commented
Solid project

2025-03-22 02:48 UTC, vanya19090 commented
😇

2025-04-21 14:12 UTC, malloy20001 reviewed
@Uzername1904

2025-04-21 14:13 UTC, malloy20001 requested changes
Telegram

2025-05-27 04:43 UTC, Winn1993 approved these changes

2025-06-05 12:07 UTC, Nylk-Cloud commented
Spam hides

2025-12-10 18:55 UTC, hangfreedom645-create approved these changes

2026-04-30 13:58 UTC, 2ds67mhnfq-svg commented on mentioned-badge-flat.svg
> +<svg width="110" height="20" viewBox="0 0 110 20" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><title>Mentioned in an Awesome list</title><defs><path d="M53.57 3.52h-
Go

2026-06-19 23:21 UTC, Samialmj commented
3716570c0a6245589f89c75ca1289dfb198e937a

2026-10-17 06:04 UTC, eddialarrm-ai reviewed
3716570c0a6245589f89c75ca1289dfb198e937a

2026-10-29 16:13 UTC, ssen1ggem22-prog commented
> 3716570c0a6245589f89c75ca1289dfb198e937a