Add Formal Languages and Compilers
sindresorhus/awesome pull request #1835
Opened 2020-07-26 00:21 UTC by patrickporto

https://github.com/patrickporto/awesome-compilers-languages

Programming language design, domain specific languages and homebrew compilers

I confirm I've read and complied with the below requirements 🖖

2020-07-26 15:37 UTC, patrickporto commented
unicorn

2020-08-03 01:58 UTC, Sea-n commented on readme.md
> +- [Formal Languages & Compilers](https://github.com/patrickporto/awesome-compilers-languages#readme) - Programming language design, domain specific languages and homebrew compilers
The description should end in a dot.

2020-08-03 09:39 UTC, probonopd commented
Hi @patrickporto. As per [the guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list),

> Entries have a description, unless the title is descriptive enough by itself. It rarely is though.

Please add descriptions to the links.

2020-09-02 20:14 UTC, JoseDeFreitas requested changes
According to the [guidelines of the PRs and the list](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md):
> The default branch should be named main, not master.

The default branch in the repository is `master`, you must change it to `main`.

2020-09-30 00:33 UTC, sindresorhus commented
I think the list is a good idea, but it needs more work and content before being something that can be added here.

I also don't see the point of linking to every part of a multi-part tutorial. Linking to the first lesson should be enough.

I'm going to close this for now, but happy to reconsider in the future when the list is more mature and has more content.

2020-09-30 00:33 UTC, closed without merging