add smart contract security
sindresorhus/awesome pull request #2258
Opened 2022-05-10 07:53 UTC by saeidshirazi

add A curated list of Smart Contract Security materials and resources For Researchers

2022-05-10 07:56 UTC, saeidshirazi commented
add new curated awesome list

2022-05-11 06:07 UTC, sindresorhus commented
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

2022-05-22 10:02 UTC, IAmCoder requested changes

2022-05-22 10:02 UTC, IAmCoder commented on readme.md
> +- [Awesome-Android-Security](https://github.com/saeidshirazi/awesome-android-security)
```suggestion
- [Awesome-Android-Security](https://github.com/saeidshirazi/awesome-android-security#readme)
```

2022-05-22 10:02 UTC, IAmCoder commented on readme.md
> +- [Smart Contract Security](https://github.com/saeidshirazi/Awesome-Smart-Contract-Security)
The URL to should end in `#readme`:
```suggestion
- [Smart Contract Security](https://github.com/saeidshirazi/Awesome-Smart-Contract-Security#readme)
```

2022-06-05 11:10 UTC, closed without merging

2022-09-21 18:16 UTC, DevilDevaa commented
Vbnj

2022-09-21 18:17 UTC, DevilDevaa commented
> add A curated list of Smart Contract Security materials and resources For Researchers
> 
>