Add Monolith Architecture
sindresorhus/awesome pull request #2502
Opened 2023-01-26 14:41 UTC by canerbasaran

**[https://github.com/canerbasaran/awesome-monolith#readme]**

**[List of content describing the benefits of starting projects with a monolith architecture]**

2023-01-26 14:55 UTC, jluterek commented
This reads as anti-microservices. Is that something to build a community around and more importantly... is it awesome?

2023-01-26 15:40 UTC, canerbasaran commented
> This reads as anti-microservices. Is that something to build a community around and more importantly... is it awesome?

According to this discourse, I'd say microservices are anti-monolith. There are many unsuccessful projects started with Microservices. Microservices aren't a silver bullet. You should choose the architecture according to the need. Nothing gives a magic solution.

2023-01-29 12:10 UTC, mic4aelx504 approved these changes

2023-01-29 12:10 UTC, mic4aelx504 commented on readme.md
>  - [Computational Biology](https://github.com/inoue0426/awesome-computational-biology#readme) - Computational approaches applied to problems in biology.
E

2023-01-29 12:24 UTC, mic4aelx504 approved these changes

2023-01-29 12:25 UTC, mic4aelx504 approved these changes

2023-01-29 12:26 UTC, mic4aelx504 requested changes
Go

2023-01-30 10:40 UTC, sindresorhus commented
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

2023-01-30 13:05 UTC, andrzejsydor approved these changes

2023-01-31 18:34 UTC, vhladiienko commented
Hi @canerbasaran 

I don't think the linter will pass. You can run it yourself locally by executing:

`npx awesome-lint https://github.com/canerbasaran/awesome-monolith`

But make sure you do it at least twice, as it currently stops linting at the `remark-lint:awesome-toc` issue, whereas I can see some other stuff that should not pass, e.g. wrong list entry formatting (you should have dashes between a link and a description).

2023-02-05 12:51 UTC, canerbasaran commented
Thanks @vhladiienko for suggestions

2023-04-23 14:42 UTC, sindresorhus commented
You are not following the formatting expected for Awesome lists.

2023-04-23 14:43 UTC, sindresorhus commented
I think in general the list needs more work. It feels a bit unfinished and not up to the quality expected from Awesome lists.

2023-04-23 14:43 UTC, sindresorhus commented on readme.md
> +- [Monolith Architecture](https://github.com/canerbasaran/awesome-monolith#readme) - Traditional model of a software program.
The description is not very useful. It doesn't actually say what a monolith is.

2023-04-23 14:44 UTC, pee563 commented
> You are not following the formatting expected for Awesome lists.

So someone is in my account controlling aspects of my phone. I have an idea who it is. It's is causing me not to be able to feed my family because he is shutting work apps.

2023-04-23 14:50 UTC, dontbethatguy209 commented
Please advise, many attempts to figure out objective but still not getting it. What can yoh do to help?

Sent via the Samsung Galaxy S21 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Sindre Sorhus ***@***.***>
Sent: Sunday, April 23, 2023 11:48:16 AM
To: sindresorhus/awesome ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [sindresorhus/awesome] Add Monolith Architecture (PR #2502)


You are not following the formatting expected for Awesome lists.

—
Reply to this email directly, view it on GitHub<https://github.com/sindresorhus/awesome/pull/2502#issuecomment-1519083511>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AULFDLPF4NCVC2SHD6TUNK3XCU6LBANCNFSM6AAAAAAUHSPG34>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-04-26 12:41 UTC, andrzejsydor approved these changes

2023-05-01 21:36 UTC, closed without merging

2023-05-06 03:09 UTC, Simeon221 commented
091eefb4d3b2903fb15d94316e0c64ce9072db42