Add Microsoft Sentinel
sindresorhus/awesome pull request #2753
Opened 2023-08-18 17:15 UTC by kfriede

https://aka.ms/awesome-sentinel

Resources for Microsoft Azure Sentinel and related KQL, SIEM, and SOAR functionality 

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- [✅] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it. **Instead use [#2242](https://github.com/sindresorhus/awesome/issues/2242) for incubation visibility**.
- [✅] **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- [✅] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments pointing out lint violation are allowed, but does **not** count as a review.
    - https://github.com/sindresorhus/awesome/pull/2736
    - https://github.com/sindresorhus/awesome/pull/2647
- [✅] You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/main/create-list.md).
- [✅] This pull request has a title in the format `Add Name of List`. It should not contain the word `Awesome`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `add Swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- [✅] Your entry here should include a short description about the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- [✅] Your entry should be added at the bottom of the appropriate category.
- [✅] The title of your entry should be title-cased and the URL to your list should end in `#readme`.
	- Example: `- [Software Architecture](https://github.com/simskij/awesome-software-architecture#readme) - The discipline of designing and building software.`
- [✅] No blockchain-related lists.
- [✅] The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [✅] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [✅] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- [✅] The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [✅] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- [✅ ] It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- [✅] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- [✅] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- [✅] Non-generated Markdown file in a GitHub repo.
- [✅] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [✅] Not a duplicate. Please search for existing submissions.
- [✅] Only has awesome items. Awesome lists are curations of the best, not everything.
- [✅] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [✅] Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to maximum half the width of the original image.
- [✅] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [✅] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- [✅] Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- Must not feature `Contributing` or `Footnotes` sections.
- [✅] Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- [✅] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. Casing is up to you.
	- It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- The section should not appear in the Table of Contents.
- [✅] All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- [✅] Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The descr [...]

2023-08-18 19:55 UTC, sindresorhus commented
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

2023-08-21 10:11 UTC, kfriede commented
@sindresorhus I went through line-by-line when I checked everything off. Would you care to inform me what I'm missing so I can fix it?

2023-08-21 11:21 UTC, The-Debarghya approved these changes

2023-08-22 20:13 UTC, bdalalhaljwysm commented
def fibonacci(n)
  return n if ( 0..1 ).include? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls
end

2023-08-23 12:48 UTC, kfriede commented
unicorn 🦄

2023-09-02 10:41 UTC, donBarbos commented
It seems [this](https://github.com/reprise99/awesome-kql-sentinel) and [this](https://github.com/cylaris/awesomekql) repositories already covers your topic

Also, your repository may not fit these criteria:
```markdown
- [ ] It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
```

2023-10-16 05:11 UTC, iamhonest1 reviewed
✌️

2023-10-16 11:10 UTC, Gnssrl requested changes

2023-10-16 11:10 UTC, Gnssrl commented on readme.md
>  - [Password Cracking](https://github.com/n0kovo/awesome-password-cracking#readme) - The process of recovering passwords from data that has been stored in or transmitted by a system in scrambled form.
Ho

2023-10-24 23:50 UTC, infosecB commented
- Recommend renaming repo to "awesome-azure-sentinel" or "awesome-microsoft-sentinel"
- Pull request title should match name of repo (e.g. without above change, "Add Sentinel")

2023-10-25 11:36 UTC, kfriede commented
> * Recommend renaming repo to "awesome-azure-sentinel" or "awesome-microsoft-sentinel"
> * Pull request title should match name of repo (e.g. without above change, "Add Sentinel")

Updated repository name, no PR name change required (since repository name now matches PR)

2023-10-25 11:37 UTC, kfriede commented
unicorn 🦄

2023-12-02 15:11 UTC, emmanuelgautier reviewed
Nice list.

You have some missing punctuation warnings here : https://github.com/kfriede/awesome-microsoft-sentinel/actions/runs/6644291312/job/18053167510#step:3:10

2024-02-14 08:11 UTC, sindresorhus commented on readme.md
> +- [Microsoft Sentinel](https://github.com/kfriede/awesome-microsoft-sentinel#readme) - Microsoft Sentinel cloud-native SIEM/SOAR solution.
The description should not contain the list title. Also not clear what SIEM/SOAR is. Needs a better description in general.

2024-02-14 08:11 UTC, sindresorhus commented
The list is a bit thin on content.

2024-02-14 08:12 UTC, sindresorhus commented
It's also not following multiple of the guidelines, like `.` at the end of descriptions. I suggest working on it some more and try submitting it again at a later point (at least wait 6 months).

2024-02-14 08:12 UTC, closed without merging