Add Awesome Pentest Cheat Sheets
sindresorhus/awesome pull request #3068
Opened 2024-06-02 23:37 UTC by ByteSnipers

Added Awesome Pentest Cheat Sheets

**URL: https://github.com/ByteSnipers/awesome-pentest-cheat-sheets**

**Awesome Pentest Cheat Sheets contains a lot of security and pentesting related information. The list has a huge list of very sorted and selected resources, which can save a lot of time to any security oriented people. This list was started 2017 and was improved over the years. The initial awesome pentest cheat sheets collects over 3.8k stars**

2024-06-02 23:41 UTC, sindresorhus commented
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

2024-06-04 04:15 UTC, Bendak09 approved these changes

2024-06-14 05:53 UTC, Polycarbohydrate commented
It appears that many of your items do not have any description. You also need to review at least 2 pull requests before making your own pull request.

Additionally running the linter on your repo, the following errors are given:
```
  README.md:323:3
  ×    9:1    ToC item "Security Talks and Videos" does not match corresponding heading "🖥 Security Talks and  Videos"                                            remark-lint:awesome-toc
  ×    9:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#-security-talks-and-videos                                                            remark-lint:double-link
  ×   11:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#-mobile-pentesting                                                                    remark-lint:double-link
  ×   12:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#%EF%B8%8F-cloud-pentesting                                                            remark-lint:double-link
  ×   13:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#active-directory                                                                      remark-lint:double-link
  ×   14:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#-pentest-methodology                                                                  remark-lint:double-link
  ×   15:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#-privilege-escalation                                                                 remark-lint:double-link
  ×   16:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#%EF%B8%8F-web-pentesting                                                              remark-lint:double-link
  ×   17:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#binary-exploitation                                                                   remark-lint:double-link
  ×   18:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#learning-platforms                                                                    remark-lint:double-link
  ×   19:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#bug-bounty                                                                            remark-lint:double-link
  ×   20:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#tools                                                                                 remark-lint:double-link
  ×   21:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/?tab=readme-ov-file#payloads-1                                                         remark-lint:double-link
  ×   22:3    https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/?tab=readme-ov-file#programming                                                        remark-lint:double-link
  ×   60:100  Unexpected reference to undefined definition, expected corresponding definition (pdf) for a link or escaped opening bracket (\[) for regular text  remark-lint:no-undefined-references
  ×  243:3    https://owasp.org/www-project-vulnerable-web-applications-directory/#div-online                                                                    remark-lint:double-link
  ×  251:3    https://owasp.org/www-project-vulnerable-web-applications-directory/#div-offline                                                                   remark-lint:double-link
  ×  323:3    Don’t pad link with inner spaces                                                                                                                   remark-lint:no-inline-padding

  19 errors
  ```
  
For the first error just make your title for the header `🖥 Security Talks and  Videos` the same by either removing the emoji or from the header or adding the emoji to the title in the Table of Contents(ToC).

The double-link errors can be easily solved by changing the links to `#(Your header here)`. Example: `https://github.com/ByteSnipers/awesome-pentest-cheat-sheets/#-security-talks-and-videos` ---> `#-security-talks-and-videos`.

Then the last issue needs to be fixed too. (no-inline-padding)

2024-06-24 22:13 UTC, IAmCoder requested changes

2024-06-27 07:58 UTC, ByteSnipers commented
I've update the repository, but I still have some issues, what I cannot solve, because I cannot identify why they are issues.

 ✖   15:1  ToC item "Privilege Escalation" does not match corresponding heading "Web Pentesting"  remark-lint:awesome-toc
  ✖  243:3  https://owasp.org/www-project-vulnerable-web-applications-directory/#div-online        remark-lint:double-link
  ✖  251:3  https://owasp.org/www-project-vulnerable-web-applications-directory/#div-offline       remark-lint:double-link
  ✖  323:3  Don’t pad link with inner spaces                                                       remark-lint:no-inline-padding

2024-07-03 17:10 UTC, tyaga001 commented
I run your repo in linting and can see some errors are still need to be resolved. 
![image](https://github.com/sindresorhus/awesome/assets/16003228/c6263f1d-788e-4a7e-a013-bd03e59828b5)

2024-07-14 08:48 UTC, 0xAnalyst commented
This looks good. Can I suggest you create a separate folder for Azure Security Architecture and put everything about it there or maybe you can create a separate awesome list for Azure Security Architecture?

2024-07-14 08:58 UTC, 0xAnalyst commented
Apart from fixing liniting issues I suggest you add a books sections and books related to book bountry web penetration testing mobile app pentesting....etc

2024-07-14 09:41 UTC, 0xAnalyst requested changes
Add it to the end of the list

2024-07-24 04:05 UTC, hstsethi commented
>  This pull request has a title in the format Add Name of List. It should not contain the word Awesome. 

As per the guidelines, the title of the pull request should be "add Pentest Cheat Sheets".

2024-08-11 05:17 UTC, Goop-arsh reviewed
Thx

2024-08-11 05:18 UTC, Goop-arsh reviewed
Thx

2024-10-22 18:11 UTC, closed without merging