Update readme.md
sindresorhus/awesome pull request #3223
Opened 2024-09-27 19:23 UTC by tarikozdemir

ABP Framework added to Platforms

**[Insert URL to the list here]**

**[Explain what this list is about and why it should be included here]**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- [ ] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it. **Instead use [#2242](https://github.com/sindresorhus/awesome/issues/2242) for incubation visibility**.
- [ ] **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- [ ] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments pointing out lint violation are allowed, but does **not** count as a review.
- [ ] You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/main/create-list.md).
- [ ] This pull request has a title in the format `Add Name of List`. It should not contain the word `Awesome`.
	- ✅ `Add Swift`
	- ✅ `Add Software Architecture`
	- ❌ `Update readme.md`
	- ❌ `Add Awesome Swift`
	- ❌ `Add swift`
	- ❌ `add Swift`
	- ❌ `Adding Swift`
	- ❌ `Added Swift`
- [ ] Your entry here should include a short description of the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb. It should not contain the name of the list.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- [ ] Your entry should be added at the bottom of the appropriate category.
- [ ] The title of your entry should be title-cased and the URL to your list should end in `#readme`.
	- Example: `- [Software Architecture](https://github.com/simskij/awesome-software-architecture#readme) - The discipline of designing and building software.`
- [ ] No blockchain-related lists.
- [ ] The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [ ] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [ ] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- [ ] The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [ ] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- [ ] It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- [ ] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- [ ] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- [ ] Non-generated Markdown file in a GitHub repo.
- [ ] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [ ] Not a duplicate. Please search for existing submissions.
- [ ] Only has awesome items. Awesome lists are curations of the best, not everything.
- [ ] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [ ] Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to a maximum of half the width of the original image.
	- Don't include both a title saying `Awesome X` and a logo with `Awesome X`. You can put the header image in a `#` (Markdown header) or `<h1>`.
- [ ] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [ ] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- [ ] Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- Must not feature `Contributing` or `Footnotes` sections.
- [ ] Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- [ ] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. The casing is up to you.
	- It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- The section should not appear in the Table of Contents.
- [ ] All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- [ ] Has consistent formatting and proper spelling/grammar.
	- The link  [...]

2024-09-27 21:41 UTC, sindresorhus commented
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

2024-09-28 01:55 UTC, 0PandaDEV reviewed
Below is a list of changes you should make to comply with the awesome guidelines. To check your list for errors like these, you can run [awesome-lint](https://github.com/sindresorhus/awesome-lint) list with this command:
```bash
npx awesome-lint https://github.com/abpframework/awesome-abp
```
```bash
README.md:3:1
  ✖    1:1    Missing file contributing.md                                  remark-lint:awesome-contributing
  ✖    1:1    Awesome list must reside in a valid git repository            remark-lint:awesome-github
  ✖    1:1    Missing or invalid Table of Contents                          remark-lint:awesome-toc
  ✖    3:1    Unexpected character ! at end of heading, remove it           remark-lint:no-heading-punctuation
  ✖    9:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   10:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   11:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   12:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   13:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   14:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   15:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   16:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   17:3    Invalid list item link URL                                    remark-lint:awesome-list-item
  ✖   23:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   23:3    Invalid list item link                                        remark-lint:awesome-list-item
  ✖   24:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   24:3    Invalid list item link                                        remark-lint:awesome-list-item
  ✖   25:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   25:3    Invalid list item link                                        remark-lint:awesome-list-item
  ✖   25:5    https://abp.io/community/                                     remark-lint:double-link
  ✖   26:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   26:3    Invalid list item link                                        remark-lint:awesome-list-item
  ✖   30:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   30:4    Invalid list item link                                        remark-lint:awesome-list-item
  ✖   31:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   31:4    Invalid list item link                                        remark-lint:awesome-list-item
  ✖   32:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   32:4    Invalid list item link                                        remark-lint:awesome-list-item
  ✖   32:6    Text "stackoverflow" should be written as "Stack Overflow"    remark-lint:awesome-spell-check
  ✖   33:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   33:4    Invalid list item link                                        remark-lint:awesome-list-item
  ✖   33:6    Text "github" should be written as "GitHub"                   remark-lint:awesome-spell-check
  ✖   37:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   37:56   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   43:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   43:84   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   44:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   44:59   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   45:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   45:89   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   55:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   56:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   57:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   65:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   65:85   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   66:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   66:62   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   67:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   67:46   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   68:3    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   68:84   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   69:3    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   69:65   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   81:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   81:56   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   82:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   82:68   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   83:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   83:72   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   84:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   84:51   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   84:118  https://abp.io/docs/latest/Modules/Cms-Kit/Index              remark-lint:double-link
  ✖   85:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   85:3    https://abp.io/docs/latest/Modules/Cms-Kit/Index              remark-lint:double-link
  ✖   85:62   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   86:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   86:50   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   87:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style
  ✖   87:78   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖   88:1    Unexpected unordered list marker *, expected -                remark-lint:unordered-list-marker-style [...]

2024-09-28 01:59 UTC, 0PandaDEV requested changes
Your list is unlicensed the awesome guidelines recommend a license like [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/legalcode.en).

2024-09-28 06:44 UTC, AnirudhG07 commented
1) please add "awesome" and "awesome-list" as tags
2) also a Awesome badge at the top next to the name as mentioned in the repo rules

2024-09-28 07:13 UTC, deiv67 approved these changes
aprovar

2024-10-21 11:39 UTC, lnxpy reviewed
You've missed to include the badge in the README file. Include any of the following items next to the awesome list title.

```md
[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)
[![Awesome](https://awesome.re/badge-flat.svg)](https://awesome.re)
[![Awesome](https://awesome.re/badge-flat2.svg)](https://awesome.re)
```

2024-10-23 12:37 UTC, Jogai commented
This is not an awesome list. Its just a list of resources by abp. Feels more like marketing than anything else.

2024-10-28 16:34 UTC, Axorax commented
The title and description on the top and then having language translations would look nicer. Also there is no awesome badge.

2024-11-11 17:56 UTC, idematos reviewed
The URL to your list should end in `#readme.`

2024-11-11 17:56 UTC, idematos commented on readme.md
> +- [ABP Framework](https://github.com/abpframework/awesome-abp) - The Web App Platform for .NET Developers
```suggestion
- [ABP Framework](https://github.com/abpframework/awesome-abp#readme) - The Web App Platform for .NET Developers
```

2024-11-12 10:48 UTC, itsmeadarsh2008 commented
> Awesome ABP!
The title shouldn't include any special characters.

Try rewriting the keywords as ABP Community ✔️  instead of using slashes. [abp.io/community](https://abp.io/community/)  ❌
Do the same with socials like Twitter (use the word X now), StackOverflow, and GitHub.

2024-12-13 23:59 UTC, Kordh63 commented
What is lacking

2025-05-15 11:38 UTC, sindresorhus commented
Not an awesome list.

2025-05-15 11:38 UTC, closed without merging