Add Red-Teaming LLMs
sindresorhus/awesome pull request #3247
Opened 2024-10-20 17:32 UTC by dapurv5

**https://github.com/dapurv5/awesome-red-teaming-llms**

**Red-teaming techniques and defenses for Large Language Models (LLMs).**

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

## Requirements for your pull request

- [x] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.
- [x] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	I have reviewed the following PRs: [#3234](https://github.com/sindresorhus/awesome/pull/3234) and [#3232](https://github.com/sindresorhus/awesome/pull/3232).
- [x] You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/main/create-list.md).
- [x] This pull request has a title in the format `Add Name of List`.
- [x] Your entry here should include a short description of the project/theme of the list.
- [x] Your entry should be added at the bottom of the appropriate category.
- [x] The title of your entry should be title-cased and the URL to your list should end in `#readme`.
- [x] No blockchain-related lists.
- [x] The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [x] **Has been around for at least 30 days.**
- [x] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues.
- [x] The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [x] **Includes a succinct description of the project/theme at the top of the readme.**
- [x] It's the result of hard work and the best I could possibly produce.
- [x] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
- [x] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics).
- [x] Not a duplicate.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs.
- [x] Includes a project logo/illustration whenever possible.
- [x] Entries have a description, unless the title is descriptive enough by itself.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
- [x] Has a Table of Contents section.
- [x] Has an appropriate license.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines).
- [x] All non-important but necessary content is grouped in a `Footnotes` section at the bottom of the readme.
- [x] Has consistent formatting and proper spelling/grammar.
- [x] Does not use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- [x] Does not include a CI (e.g. GitHub Actions) badge.
- [x] Does not include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme.

2024-10-20 18:27 UTC, sindresorhus commented
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

2024-10-21 11:29 UTC, lnxpy reviewed
I think you should use a valid approach for listing the items as the ToC has no depth and lists are depicted as tables!

2024-10-28 11:34 UTC, cvyl requested changes
I understand the approach but I think a ToC would be better instead of tables.

2024-10-29 08:42 UTC, itsmohitnarayan approved these changes

2024-11-11 17:17 UTC, idematos reviewed
The URL to your list should end in `#readme`.

2024-11-11 17:17 UTC, idematos commented on readme.md
> +- [Red-Teaming LLMs](https://github.com/dapurv5/awesome-red-teaming-llms) - Systematizing LLM security: A threat model for red-teaming attacks and defense strategies.
```suggestion
- [Red-Teaming LLMs](https://github.com/dapurv5/awesome-red-teaming-llms#readme) - Systematizing LLM security: A threat model for red-teaming attacks and defense strategies.
```

2024-11-12 09:39 UTC, idematos commented
Hi @dapurv5, thank you for updating the PR! Here are a couple more things I noticed on your list:

- I think the `Introduction` and `Attack Surface` sections are too long. I would recommend removing them and instead adding a brief definition of the theme at the top of the list. Also, the list's description would be better presented as a quote (see [example](https://github.com/idematos/awesome-permacomputing?tab=readme-ov-file#awesome-permacomputing-)).
- The table of contents should then start at `Attacks`, where the list begins, with a maximum depth of one. You can retain titles with greater depth within the list itself, but they should not appear in the table of contents.

> ## Contents
> 
> - [Attacks](#attacks)
>   - [Jailbreak Attack](#jailbreak-attack)
>   - [Direct Attack](#direct-attack)
>   - [Infusion Attack](#infusion-attack)
>   - [Inference Attack](#inference-attack)
>   - [Training Time Attack](#training-time-attack)
> - [Defenses](#defenses)

2024-11-27 11:51 UTC, zhjwpku approved these changes
LGTM

2024-11-27 13:04 UTC, itsmohitnarayan approved these changes

2025-01-21 18:11 UTC, DanailMinchev commented on readme.md
> +- [Red-Teaming LLMs](https://github.com/dapurv5/awesome-red-teaming-llms#readme) - Systematizing Large Language Model Security: Attack Taxonomy, Defense Framework, and Red-Teaming Protocols
Missing `.` in the of the sentence:
<img width="791" alt="image" src="https://github.com/user-attachments/assets/120843d6-c5e2-4210-96e6-8d5dc96d3fec" />

```
Systematizing Large Language Model Security: Attack Taxonomy, Defense Framework, and Red-Teaming Protocols.
```

2025-02-24 11:23 UTC, itsmohitnarayan approved these changes

2025-07-08 18:49 UTC, colbytimm commented
Can you add attacks and defence tables in the main readme instead of having them as separate markdown files. Also wonder if you should link the paper as a reference in the readme vs having it in the description.

2025-10-27 17:51 UTC, closed without merging