Add PostgreSQL hacking
sindresorhus/awesome pull request #3282
Opened 2024-11-23 15:16 UTC by zhjwpku

https://github.com/pghacking/awesome-postgres-hacking

A curated list of awesome PostgreSQL hacking resources.

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

## Requirements for your pull request

- [x] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it. **Instead use [#2242](https://github.com/sindresorhus/awesome/issues/2242) for incubation visibility**.
- [x] **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- [x] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
	I reviewed #3247, #3283 and #3256
- [x] You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/main/create-list.md).
- [x] This pull request has a title in the format `Add Name of List`. It should not contain the word `Awesome`.
- [x] Your entry here should include a short description of the project/theme of the list. **It should not describe the list itself.** The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb. It should not contain the name of the list.
	- ✅ `- [iOS](…) - Mobile operating system for Apple phones and tablets.`
	- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
	- ❌ `- [iOS](…) - Resources and tools for iOS development.`
	- ❌ `- [Framer](…)`
	- ❌ `- [Framer](…) - prototyping interactive UI designs`
- [x] Your entry should be added at the bottom of the appropriate category.
- [x] The title of your entry should be title-cased and the URL to your list should end in `#readme`.
	- Example: `- [Software Architecture](https://github.com/simskij/awesome-software-architecture#readme) - The discipline of designing and building software.`
- [x] No blockchain-related lists.
- [x] The suggested Awesome list complies with the below requirements.

## Requirements for your Awesome list

- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [x] Run [`awesome-lint`](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- [x] The default branch should be named [`main`, not `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- ✅ `Mobile operating system for Apple phones and tablets.`
	- ✅ `Prototyping interactive UI designs.`
	- ❌ `Resources and tools for iOS development.`
	- ❌ `Awesome Framer packages and tools.`
- [x] It's the result of hard work and the best I could possibly produce.
	**If you have not put in considerable effort into your list, your pull request will be immediately closed.**
- [x] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
	- ✅ `awesome-swift`
	- ✅ `awesome-web-typography`
	- ❌ `awesome-Swift`
	- ❌ `AwesomeWebTypography`
- [x] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: `# Awesome Name of List`.
	- ✅ `# Awesome Swift`
	- ✅ `# Awesome Web Typography`
	- ❌ `# awesome-swift`
	- ❌ `# AwesomeSwift`
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [x] Not a duplicate. Please search for existing submissions.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [x] Includes a project logo/illustration whenever possible.
	- Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- The image should link to the project website or any relevant website.
	- **The image should be high-DPI.** Set it to a maximum of half the width of the original image.
	- Don't include both a title saying `Awesome X` and a logo with `Awesome X`. You can put the header image in a `#` (Markdown header) or `<h1>`.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
	- Should be placed on the right side of the readme heading.
		- Can be placed centered if the list has a centered graphics header.
	- Should link back to this list.
- [x] Has a Table of Contents section.
	- Should be named `Contents`, not `Table of Contents`.
	- Should be the first section in the list.
	- Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
	- Must not feature `Contributing` or `Footnotes` sections.
- [x] Has an appropriate license.
	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
	- A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org).
	- Place a file named `license` or `LICENSE` in the repo root with the license text.
	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines).
	- The file should be named `contributing.md`. The casing is up to you.
	- It can optionally be linked from the readme in a dedicated section titled `Contributing`, positioned at the top or bottom of the main content.
	- The section should not appear in the Table of Contents.
- [x] All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.
- [x] Has consistent formatting and proper spelling/grammar.
	- The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- The description starts with an uppercase character and ends with a period.
	- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Does not use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- [x] Does not include a CI (e.g. GitHub Actions) badge.<br>You can still use a CI for linting, but the badge has no value in the readme.
- [x] Does not include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme. The Awesome badge is enough.

**Go to the top and read it again.**

2024-11-23 15:23 UTC, sindresorhus commented
Thanks for making an Awesome list! 🙌

It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

2024-11-25 10:52 UTC, bozaci requested changes
Your README file does not seem to conform to **Awesome Lint** rules. Therefore, you are getting errors in `Checks > awesome-lint`. To solve the problem, you need to run the following command in the main directory of your project:

`npx awesome-lint`

Upon completion of the command, make sure to fix all errors and get the `✔ Linting` message. For more information about **Awesome Lint** [click here](https://github.com/sindresorhus/awesome-lint).

2024-11-25 13:55 UTC, zhjwpku commented
> Thanks for making an Awesome list! 🙌
> 
> It looks like you didn't read the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) closely enough. I noticed multiple things that are not followed. Try going through the list point for point to ensure you follow it. I spent a lot of time creating the guidelines so I wouldn't have to comment on common mistakes, and rather spend my time improving Awesome.

I've edit the repo conform to awesome-lint, there is one requirement that not satisfied,
since I am adding an entry related to Postgres, I think it will be better that this
entry be listed below the Postgres entry.

2024-11-25 14:49 UTC, bozaci requested changes
There is no issue with `npx awesome-lint https://github.com/pghacking/awesome-postgres-hacking`; it is now `✅ Linting` successfully.

It would be better to add it to the README.md file of the Awesome repository as follows because other projects have added it this way.

- [PostgreSQL](https://github.com/dhamaniasad/awesome-postgres#readme) - Object-relational database.
    - [Hacking](https://github.com/pghacking/awesome-postgres-hacking#readme) - PostgreSQL hacking resources.

There is also a description of “PostgreSQL hacking resources.” It should not start with the title.

2024-11-26 02:14 UTC, zhjwpku commented
> There is no issue with `npx awesome-lint https://github.com/pghacking/awesome-postgres-hacking`; it is now `✅ Linting` successfully.
> 
> It would be better to add it to the README.md file of the Awesome repository as follows because other projects have added it this way.
> 
> * [PostgreSQL](https://github.com/dhamaniasad/awesome-postgres#readme) - Object-relational database.
>   
>   * [Hacking](https://github.com/pghacking/awesome-postgres-hacking#readme) - PostgreSQL hacking resources.
> 
> There is also a description of “PostgreSQL hacking resources.” It should not start with the title.

Changed as a subentry.
Non english native speaker, what do you mean by saying "It should not start with the title"?
Can you be specific which part should be changed?

2024-11-26 11:05 UTC, bozaci commented
Your Description: **PostgreSQL hacking resources.**
PostgreSQL, present at the beginning of the description, should not be at the beginning. It would be best if you corrected the description accordingly, other pull requests are requested this way.

Example:

- [PostgreSQL](https://github.com/dhamaniasad/awesome-postgres#readme) - Object-relational database.
  - [Hacking](https://github.com/pghacking/awesome-postgres-hacking#readme) - Resources for PostgreSQL hacking.

2024-11-26 16:29 UTC, bozaci requested changes
Finally, as far as I can see you have added a pull request review, but no ‘approved’, ‘request changes’ or any comments.

2024-11-27 04:12 UTC, zhjwpku commented
> Finally, as far as I can see you have added a pull request review, but no ‘approved’, ‘request changes’ or any comments.

I don't remember I add a pull request review, I just do quote reply. I had re-requested your review after I did some change, I'm not sure if mean that.

2024-11-27 11:20 UTC, bozaci commented
**The one you added**: You should review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).
I have reviewed https://github.com/sindresorhus/awesome/pull/3247 and https://github.com/sindresorhus/awesome/pull/3256

**Checklist request**: You should review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).
Try to prioritise unreviewed PRs, but you can also add more comments to reviewed PRs. Review the following list when reviewing. This requirement is to help the Awesome project become self-sustaining. Leave a comment here about which PRs you have reviewed. You are expected to make a good effort and be thorough. Look at previous PR reviews for inspiration. Just commenting ‘looks good’ or just marking the pull request as approved doesn't count! You really need to point out errors or suggestions for improvement. Comments pointing out a lint violation are allowed, but do not count as a review.

---

I think there has been a slight misunderstanding here. It is not enough to say ‘I have reviewed these PRs’. The checklist expects you to do a detailed review and share any shortcomings or suggestions for improvement. For example, you can look at previous reviews and get inspired. So it would be best if you made a more in-depth evaluation.

2024-11-27 11:55 UTC, zhjwpku commented
> **The one you added**: You should review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen). I have reviewed #3247 and #3256
> 
> **Checklist request**: You should review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen). Try to prioritise unreviewed PRs, but you can also add more comments to reviewed PRs. Review the following list when reviewing. This requirement is to help the Awesome project become self-sustaining. Leave a comment here about which PRs you have reviewed. You are expected to make a good effort and be thorough. Look at previous PR reviews for inspiration. Just commenting ‘looks good’ or just marking the pull request as approved doesn't count! You really need to point out errors or suggestions for improvement. Comments pointing out a lint violation are allowed, but do not count as a review.
> 
> I think there has been a slight misunderstanding here. It is not enough to say ‘I have reviewed these PRs’. The checklist expects you to do a detailed review and share any shortcomings or suggestions for improvement. For example, you can look at previous reviews and get inspired. So it would be best if you made a more in-depth evaluation.

OK, I just reviewed #3283 and #3247 and left a LGTM approve message.

2024-11-28 14:51 UTC, zhjwpku commented
> Thanks for creating the list!
> 
> Please note in the guidelines:
> 
> > Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
> 
> In your list, most of the entries have none. Only the books, the first two mailing lists, and the tools have them.
> 
TBH, I think the titles are descriptive enough by themselves.

> Also, there's an empty section "Parser".

I just add for entry for parser section.

2024-11-28 14:53 UTC, lutzh approved these changes

2024-11-29 22:29 UTC, bozaci approved these changes

2024-11-30 02:53 UTC, Mohsin-82 approved these changes

2025-01-21 18:05 UTC, DanailMinchev commented on readme.md
> +	- [Hacking](https://github.com/pghacking/awesome-postgres-hacking#readme) - Resources for PostgreSQL hacking.
Looks like a whitespace here:
<img width="784" alt="image" src="https://github.com/user-attachments/assets/6825b848-e467-4af5-9a6b-10da70b338ca" />

Please remove it, so it is the same as the other entries

2025-01-22 19:47 UTC, DanailMinchev commented on readme.md
> +	- [Hacking](https://github.com/pghacking/awesome-postgres-hacking#readme) - Resources for PostgreSQL hacking.
I see, thank you, makes sense

2025-01-22 19:48 UTC, DanailMinchev commented
Please have a look at these linting errors, mainly missing dots:
<img width="715" alt="image" src="https://github.com/user-attachments/assets/0f08b6d5-0757-4adb-b274-f085aa6189dc" />

2025-01-25 09:09 UTC, closed without merging